version: '3.8'

services:
  db:
    container_name: pg_docker_gerenciamento_pessoas
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: docker-erenciamento-pessoas-db
      POSTGRES_USER: docker-user
      POSTGRES_PASSWORD: docker-password